name: tfr
channels:
- defaults
dependencies:
  - python=3.7.*
  - pip
  - pip:
    - torchviz
    - matplotlib
    - torchvision>=0.5
    - opencv
    - pillow
    - scipy
    - pytorch
    - scikit-learn
    - pandas
    - numpy
    - imageio
